#!/bin/sh
# variant mrbeam, flavor default: override hostname & custom config setting
export DIST_NAME=BeamOS
export DIST_VERSION=0.18.2
export BASE_OVERRIDE_HOSTNAME=MrBeam-XXXX
export BASE_IMAGE_ENLARGEROOT=1700

export BEAMOS_DEV=no
export MODULES="base(raspicam, network, disable-services(dev-libs(octopi, beamos)))"
# export MODULES="base(raspicam, network, disable-services(dev-libs(octopi, beamos)), password-for-sudo)"

# Proxy server
#export BASE_PYPI_INDEX="http://devpi.soll.xyz:5798/mrbeam/prod/+simple/"

export OCTOPI_OCTOPRINT_REPO_BUILD=https://github.com/mrbeam/OctoPrint.git
export OCTOPI_OCTOPRINT_REPO_SHIP=https://github.com/mrbeam/OctoPrint.git
export OCTOPI_OCTOPRINT_REPO_BRANCH=mrbeam2-stable
# export OCTOPI_OCTOPRINT_ARCHIVE=/filesystem/OctoPrint
export OCTOPI_OCTOPRINT_ARCHIVE=https://github.com/mrbeam/OctoPrint/archive/$OCTOPI_OCTOPRINT_REPO_BRANCH.zip

# disable unnecessary stuff
export OCTOPI_INCLUDE_OCTOPIPANEL=no
export OCTOPI_INCLUDE_CURAENGINE=no
export OCTOPI_INCLUDE_MJPGSTREAMER=no
export OCTOPI_INCLUDE_WIRINGPI=no
export OCTOPI_INCLUDE_FFMPEG_HLS=no

# Fix - only python2 compatible for now:
export OCTOPI_PYTHON_VERSION=python2
# Add dev repos to build up the MrBeam dependencies - Will not be kept in the image.
export DEV_LIBS_EXTRA="python2-dev libxml2-dev libxslt1-dev"

# Dev allow ssh for now
export BEAMOS_INCLUDE_SSH=yes
