#!/bin/sh
# variant mrbeam, flavor default: override hostname & custom config setting

export DIST_NAME=BeamOS
export BASE_OVERRIDE_HOSTNAME=MrBeam-XXXX
export BASE_IMAGE_ENLARGEROOT=2200
# Add the beamos module
export MODULES="base(raspicam, network, disable-services(dev-libs(octopi, beamos)), password-for-sudo)"

export OCTOPI_OCTOPRINT_REPO_BUILD=https://github.com/mrbeam/OctoPrint.git
export OCTOPI_OCTOPRINT_REPO_SHIP=https://github.com/mrbeam/OctoPrint.git
export OCTOPI_OCTOPRINT_REPO_BRANCH=mrbeam2-stable
# export OCTOPI_OCTOPRINT_ARCHIVE=/filesystem/OctoPrint
export OCTOPI_OCTOPRINT_ARCHIVE=https://github.com/mrbeam/OctoPrint/archive/$OCTOPI_OCTOPRINT_REPO_BRANCH.zip

# Where to find the ssh key to pull private repos
export BEAMOS_IOBEAM_REPO_SSH_KEY=/filesystem/bitbucket_rsa
export BEAMOS_MOUNTMANAGER_REPO_SSH_KEY=/filesystem/bitbucket_rsa
if [ "$1" = "dev" -o "$1" = "develop" ]; then
    echo "BUILDING DEV FLAVOR"
    export OCTOPI_OCTOPRINT_REPO_BRANCH=develop
    export BEAMOS_MRBEAMPLUGIN_REPO_BRANCH=develop
    export BEAMOS_MRBEAMIOBEAM_REPO_BRANCH=develop
    export BEAMOS_MRBEAMLED_REPO_BRANCH=develop
    export BEAMOS_USBMOUNTMANAGER_REPO_BRANCH=develop
    export BEAMOS_FINDMYMRBEAM_PLUGIN_REPO_BRANCH=develop
else
    echo "BUILDING STABLE FLAVOR"
fi

# uses the pypi wheel for now with python3 compatibility
# DOES NOT allow for the "spread spectrum" feature
export BEAMOS_RPI_WS281X_ARCHIVE=rpi-ws281x
export BEAMOS_MRBEAMLED_REPO_BRANCH=py3

# disable unnecessary stuff
export OCTOPI_INCLUDE_OCTOPIPANEL=no
export OCTOPI_INCLUDE_CURAENGINE=no
export OCTOPI_INCLUDE_MJPGSTREAMER=no
export OCTOPI_INCLUDE_WIRINGPI=no
export OCTOPI_INCLUDE_FFMPEG_HLS=no

# Fix - only python2 compatible for now:
export OCTOPI_PYTHON_VERSION=python2
# Add dev repos to build up the MrBeam dependencies - Will not be kept in the image.
export DEV_LIBS_EXTRA="python2-dev libxml2-dev libxslt1-dev"
# dev - enable repos little by little
# export BASE_IMAGE_RESIZEROOT=1000
export BEAMOS_INCLUDE_MRBEAMPLUGIN=yes
export OCTOPI_INCLUDE_OCTOPRINT=yes
export OCTOPI_INCLUDE_HAPROXY=yes
export BEAMOS_INCLUDE_MOUNTMANAGER=yes
export BEAMOS_INCLUDE_NETCONNECTD=no
export BEAMOS_INCLUDE_IOBEAM=yes
export BEAMOS_INCLUDE_FINDMYMRBEAM=yes
export BEAMOS_DEV=no
export BEAMOS_MRBEAMLED_BRANCH=py3

# Dev allow ssh for now
export BEAMOS_INCLUDE_SSH=yes
