#!/usr/bin/env bash

###############################################################################################
# NOTES:
#
# - Installation still via git clone and python setup and not via pip because I (Florian) was
#   not able to apply the install_extras stuff to the pip process. Afterwards the repos get
#   removed and the update should be possible via the pip update.
#
###############################################################################################

set -x

source /common.sh

function addGitHashToConfig () {
    name=$1
    hash=$(git rev-parse HEAD)
    sed -i -e "s@<$name>@$hash@g" /home/pi/.octoprint/config.yaml
}

install_chroot_fail_on_error_trap

# unpack filesystem directory
unpack /filesystem/root /
unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root

# enable first_boot_script
update-rc.d first_boot_script defaults

# install necessary dependencies
apt-get -y --force-yes install libxml2-dev libxslt-dev libjpeg8-dev hostapd dnsmasq logrotate rfkill python-pip python-smbus libyaml-dev i2c-tools avrdude

# upgrade pip and install wheel system wide
sudo pip install --upgrade pip
sudo pip install wheel

# upgrade pip and install wheel in venv
sudo -u pi /home/pi/oprint/bin/pip install --upgrade pip
sudo -u pi /home/pi/oprint/bin/pip install wheel

# install and use wheels of precached heavy duty packages
sudo -u pi /home/pi/oprint/bin/pip install --no-index --find-links=/wheels/ numpy
sudo -u pi /home/pi/oprint/bin/pip install --no-index --find-links=/wheels/ lxml
sudo -u pi /home/pi/oprint/bin/pip install --no-index --find-links=/wheels/ pillow
sudo rm -rf /wheels

# install Mr Beam Plugin
pushd /home/pi
  gitclone OCTOPI_MRBEAMPLUGIN_REPO MrBeamPlugin
  addGitHashToConfig "mrbeamhash"
  pushd MrBeamPlugin
    sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
  rm -rf MrBeamPlugin
popd

# install netconnectd
sudo systemctl disable hostapd.service
sudo systemctl disable dnsmasq.service
sed -i -e "s@#timeout 60;@timeout 60;@g" /etc/dhcp/dhclient.conf
pushd /home/pi
  gitclone OCTOPI_NETCONNECTD_REPO netconnectd
  addGitHashToConfig "netconnectddaemonhash"
  pushd netconnectd
    sudo python setup.py install
    sudo python setup.py install_extras
  popd
  rm -rf netconnectd
popd
sed -i -e "s@allow-hotplug wlan0@#allow-hotplug wlan0@g" /etc/network/interfaces
sed -i -e "s@iface wlan0-raspbian inet manual@#iface wlan0-raspbian inet manual@g" /etc/network/interfaces
sed -i -e "s@    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf@#    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf@g" /etc/network/interfaces
sudo systemctl enable netconnectd.service

# install netconnectd-plugin
pushd /home/pi
  gitclone OCTOPI_NETCONNECTD_PLUGIN_REPO OctoPrint-Netconnectd
  addGitHashToConfig "netconnectdpluginhash"
  pushd OctoPrint-Netconnectd
    sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
  rm -rf OctoPrint-Netconnectd
popd

# install findmymrbeam-plugin
pushd /home/pi
  gitclone OCTOPI_FINDMYMRBEAM_PLUGIN_REPO OctoPrint-FindMyOctoPrint
  addGitHashToConfig "findmymrbeamhash"
  pushd OctoPrint-FindMyOctoPrint
    sudo -u pi /home/pi/oprint/bin/python setup.py install
  popd
  rm -rf OctoPrint-FindMyOctoPrint
popd

# install Mr Beam shield software
pushd /home/pi
  gitclone OCTOPI_MRBEAMSHIELD_REPO pcf8575
  addGitHashToConfig "pcf8575hash"
  pushd pcf8575
    sudo cp pcf8575.service /etc/systemd/system/
    sudo systemctl enable pcf8575.service
  popd
popd

# install Mr Beam LED software
pushd /home/pi
  gitclone OCTOPI_MRBEAMLED_REPO mrbeamledstrips
  addGitHashToConfig "mrbeamledstripshash"
  pushd mrbeamledstrips
    sudo python setup.py install
    sudo python setup.py install_extras
    sudo systemctl enable mrbeam_ledstrips.service
  popd
  rm -rf mrbeamledstrips
popd

# activate ssh
pushd /boot
  touch ssh
popd

# activate i2c
echo "i2c-dev" >> /etc/modules
sed -i -e "s@#dtparam=i2c_arm=on@dtparam=i2c_arm=on@g" /boot/config.txt

# enable hardware serial
echo "dtoverlay=pi3-miniuart-bt" >> /boot/config.txt
echo "enable_uart=1" >> /boot/config.txt
sed -i -e "s@console=serial0,115200 @@g" /boot/cmdline.txt

#cleanup
apt-get clean
sudo rm /common.sh
