#!/usr/bin/env sh

# libxslt-dev required for etree in lxml package
[ -n "$DEV_LIBS_BASE" ] || DEV_LIBS_BASE="python3-dev libffi-dev libssl-dev libjpeg9-dev libxslt-dev"

[ -n "$DEV_LIBS_EXTRA" ] || DEV_LIBS_EXTRA=

# Fixed apt mirror
[ -n "$DEV_LIBS_APTMIRROR" ] || DEV_LIBS_APTMIRROR=
