#!/usr/bin/env bash
# OctoPI generation script
# Helper script that runs in a Raspbian chroot to create the OctoPI distro
# Written by Axel Soll <axel@soll.xyz>
# GPL V3
########
set -x
set -e

if [ -n "$DEV_LIBS_APTMIRROR" ];
then
    echo "Switching apt mirror in /etc/apt/sources.list to $DEV_LIBS_APTMIRROR"
    cp /etc/apt/sources.list /etc/apt/sources.list.backup
    sed -i "s@http://raspbian.raspberrypi.org/raspbian/@$DEV_LIBS_APTMIRROR@g" /etc/apt/sources.list
fi

apt-get update

apt-get -y python3-dev libffi-dev libssl-dev python2-dev

# $(echo $DEV_LIBS_BASE $DEV_LIBS_EXTRA)
