#!/usr/bin/sh
# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Alias definitions.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.config/aliases ]; then
    . ~/.config/aliases
fi

## git
parse_git_branch() {
      git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# Extend PATH
export PATH="$HOME/.local/bin:$PATH"

# prompt

RED="\[\033[0;31m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
NO_COLOUR="\[\033[0m\]"

PS1="$GREEN\u@\h$NO_COLOUR:\w$YELLOW\$(parse_git_branch)$NO_COLOUR\> "

# Show some fun(ctional) stuff when opening a shell
## Banner
figlet -cf slant BeamOS 2>/dev/null || echo "Welcome to beamOS!"
## Disclaimer in Red
{ { [ -f ~/.disclaimer ] && disc="$HOME/.disclaimer";} || { [ -f ~/.config/disclaimer ] && disc="$HOME/.config/disclaimer";};} && \
    printf "\033[0;31m" && cat "$disc" && printf "\033[0;0m"
# Show detailed info about the systemd status of these services
#systemctl --no-pager status -n 0 mrbeam_ledstrips netconnectd iobeam octoprint

# nice neofetch greeting - a bit slow though
echo # Extra newline for stylezz
neofetch --ascii "$(cat /home/pi/.config/logo_ascii)" 2>/dev/null
