#!/bin/sh
### BEGIN INIT INFO
# Provides:          beamos_first_boot
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Things to do on first startup of OctoPi
# Description:
### END INIT INFO

. /lib/lsb/init-functions
timestamp()
{
 date +"%Y-%m-%d %T"
}

do_start () {
    REBOOT=false
    logfile=/var/log/beamos_first_boot.log

}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: octopi_first_boot [start|stop]" >&2
        exit 3
        ;;
esac
