#!/bin/sh
### BEGIN INIT INFO
# Provides:          octopi_first_boot
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Things to do on first startup of OctoPi
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_start () {
    logfile=/var/log/beamos_first_boot.log
    # Do not run multiple times
    [ -f $logfile ] && return 0

    echo "Refreshing the device hostname..." >> $logfile
    [ -x /usr/bin/beamos_hostname ] && /usr/bin/beamos_hostname >> $logfile

    echo "Updating the WiFi Access Point name..." >> $logfile
    [ -x /usr/bin/reset_apname ] && /usr/bin/reset_apname >> $logfile

    # enable the usb mount manager udev rules
    rm /etc/udev/rules.d/00-mount_manager.rules

    /sbin/reboot
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: octopi_first_boot [start|stop]" >&2
        exit 3
        ;;
esac
