#!/bin/sh

#################################################################
# Choose what to install here


# MRBPLUGIN_PATH="${BASE_PIP_PACKAGES}/MrBeamPlugin"
# IOBEAM_PATH="${BASE_PIP_PACKAGES}/iobeam"
# MOUNTMANAGER_PATH="${BASE_PIP_PACKAGES}/usb_mount_manager"
TRUE_USER=pi

# Cached repos
# [ -n "$BEAMOS_MOUNTMANAGER_ARCHIVE" ] || BEAMOS_MOUNTMANAGER_ARCHIVE="${PIP_CHROOT_LOCAL_DEST}/usb_mount_manager"
# BEAMOS_NETCONNECTD_ARCHIVE="${PIP_CHROOT_LOCAL_DEST}/netconnectd"
# BEAMOS_NETCONNECTD_PLUGIN_ARCHIVE="${PIP_CHROOT_LOCAL_DEST}/OctoPrint-Netconnectd"
# [ -n "$BEAMOS_OCTO_NETCONNECTD_ARCHIVE" ] || BEAMOS_OCTO_NETCONNECTD_ARCHIVE=https://github.com/mrbeam/OctoPrint-Netconnectd/archive/mrbeam2-stable.zip
# [ -n "$BEAMOS_NETCONNECTD_ARCHIVE" ] || BEAMOS_NETCONNECTD_ARCHIVE=https://github.com/mrbeam/netconnectd/archive/master.zip

# Branches
[ -n "$BEAMOS_MRBEAMPLUGIN_REPO_BRANCH" ] || BEAMOS_MRBEAMPLUGIN_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_MRBEAMIOBEAM_REPO_BRANCH" ] || BEAMOS_IOBEAM_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_MRBEAMLED_REPO_BRANCH" ] || BEAMOS_MRBEAMLED_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_USBMOUNTMANAGER_REPO_BRANCH" ] || BEAMOS_MOUNTMANAGER_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_FINDMYMRBEAM_PLUGIN_REPO_BRANCH" ] || BEAMOS_FINDMYMRBEAM_PLUGIN_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_NETCONNECTD_REPO_BRANCH" ] || BEAMOS_NETCONNECTD_REPO_BRANCH=master
[ -n "$BEAMOS_NETCONNECTD_PLUGIN_REPO_BRANCH" ] || BEAMOS_NETCONNECTD_PLUGIN_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_SHIELDFLASHER_REPO_BRANCH" ] || BEAMOS_SHIELDFLASHER_REPO_BRANCH=master
[ -n "$BEAMOS_RPI_WS281X_REPO_BRANCH" ] || BEAMOS_RPI_WS281X_REPO_BRANCH=master

# # MrBeamPlugin
[ -n "$BEAMOS_INCLUDE_MRBEAMPLUGIN" ] || export BEAMOS_INCLUDE_MRBEAMPLUGIN=yes
# This uses the latest release as an archive
# [ -n "$BEAMOS_MRBEAMPLUGIN_ARCHIVE" ] || export BEAMOS_MRBEAMPLUGIN_ARCHIVE=$(wget -q -O - https://api.github.com/repos/mrbeam/MrBeamPlugin/releases/latest | grep "zipball_url" | cut -d : -f 2,3 | tr -d \" | tr -d ,)
[ -n "$BEAMOS_MRBEAMPLUGIN_ARCHIVE" ] || BEAMOS_MRBEAMPLUGIN_ARCHIVE=https://github.com/mrbeam/MrBeamPlugin/archive/$IOBEAM_IOBEAM_REPO_BRANCH.zip
[ -n "$BEAMOS_MRBEAMPLUGIN_REPO_SHIP" ] || export BEAMOS_MRBEAMPLUGIN_REPO_SHIP=https://github.com/mrbeam/MrBeamPlugin.git
[ -n "$BEAMOS_MRBEAMPLUGIN_REPO_BUILD" ] || BEAMOS_MRBEAMPLUGIN_REPO_BUILD=https://github.com/mrbeam/MrBeamPlugin.git

# IOBeam
[ -n "$BEAMOS_INCLUDE_IOBEAM" ] || BEAMOS_INCLUDE_IOBEAM=yes
[ -n "$BEAMOS_IOBEAM_ARCHIVE" ] || BEAMOS_IOBEAM_ARCHIVE=https://github.com/mrbeam/iobeam/archive/$BEAMOS_IOBEAM_REPO_BRANCH.zip
[ -n "$BEAMOS_IOBEAM_REPO_BUILD" ] || BEAMOS_IOBEAM_REPO_BUILD=git+ssh://git@bitbucket.org/mrbeam/iobeam.git
[ -n "$BEAMOS_IOBEAM_REPO_SHIP" ] || BEAMOS_IOBEAM_REPO_SHIP=git+ssh://git@bitbucket.org/mrbeam/iobeam.git

[ -n "$BEAMOS_INCLUDE_MRBLED" ] || BEAMOS_INCLUDE_MRBLED=yes
[ -n "$BEAMOS_MRBEAMLED_ARCHIVE" ] || BEAMOS_MRBEAMLED_ARCHIVE=https://github.com/mrbeam/FF/archive/$BEAMOS_MRBEAMLED_REPO_BRANCH.zip
[ -n "$BEAMOS_MRBEAMLED_REPO_BUILD" ] || BEAMOS_MRBEAMLED_REPO_BUILD=https://github.com/mrbeam/MrBeamLedStrips.git
[ -n "$BEAMOS_MRBEAMLED_REPO_SHIP" ] || BEAMOS_MRBEAMLED_REPO_SHIP=https://github.com/mrbeam/MrBeamLedStrips.git

# Netconnectd and Netconnectd plugin
[ -n "$BEAMOS_INCLUDE_NETCONNECTD" ] || BEAMOS_INCLUDE_NETCONNECTD=yes
[ -n "$BEAMOS_NETCONNECTD_ARCHIVE" ] || BEAMOS_NETCONNECTD_ARCHIVE=https://github.com/mrbeam/netconnectd_mrbeam/archive/$BEAMOS_NETCONNECTD_REPO_BRANCH.zip
[ -n "$BEAMOS_NETCONNECTD_REPO_BUILD" ] || BEAMOS_NETCONNECTD_REPO_BUILD=https://github.com/mrbeam/netconnectd_mrbeam.git
[ -n "$BEAMOS_NETCONNECTD_REPO_SHIP" ] || BEAMOS_NETCONNECTD_REPO_SHIP=https://github.com/mrbeam/netconnectd_mrbeam.git

[ -n "$BEAMOS_NETCONNECTD_PLUGIN_ARCHIVE" ] || BEAMOS_NETCONNECTD_PLUGIN_ARCHIVE=https://github.com/mrbeam/OctoPrint-Netconnectd/archive/$BEAMOS_NETCONNECTD_PLUGIN_REPO_BRANCH.zip
[ -n "$BEAMOS_NETCONNECTD_PLUGIN_REPO_BUILD" ] || BEAMOS_NETCONNECTD_PLUGIN_REPO_BUILD=https://github.com/mrbeam/OctoPrint-Netconnectd.git
[ -n "$BEAMOS_NETCONNECTD_PLUGIN_REPO_SHIP" ] || BEAMOS_NETCONNECTD_PLUGIN_REPO_SHIP=https://github.com/mrbeam/OctoPrint-Netconnectd.git

[ -n "$BEAMOS_INCLUDE_FINDMYMRBEAM" ] || BEAMOS_INCLUDE_FINDMYMRBEAM=yes
[ -n "$BEAMOS_FINDMYMRBEAM_ARCHIVE" ] || BEAMOS_FINDMYMRBEAM_ARCHIVE=https://github.com/mrbeam/OctoPrint-FindMyMrBeam/archive/$BEAMOS_FINDMYMRBEAM_PLUGIN_REPO_BRANCH.zip
[ -n "$BEAMOS_FINDMYMRBEAM_REPO_BUILD" ] || BEAMOS_FINDMYMRBEAM_REPO_BUILD=https://github.com/mrbeam/OctoPrint-FindMyMrBeam.git
[ -n "$BEAMOS_FINDMYMRBEAM_REPO_SHIP" ] || BEAMOS_FINDMYMRBEAM_REPO_SHIP=https://github.com/mrbeam/OctoPrint-FindMyMrBeam.git

[ -n "$BEAMOS_INCLUDE_SHIELDFLASHER" ] || BEAMOS_INCLUDE_SHIELDFLASHER=yes
[ -n "$BEAMOS_SHIELDFLASHER_ARCHIVE" ] || BEAMOS_SHIELDFLASHER_ARCHIVE=https://github.com/mrbeam/shield_flasher/archive/$BEAMOS_SHIELDFLASHER_REPO_BRANCH.zip
[ -n "$BEAMOS_SHIELDFLASHER_REPO_BUILD" ] || BEAMOS_SHIELDFLASHER_REPO_BUILD=https://github.com/mrbeam/shield_flasher.git
[ -n "$BEAMOS_SHIELDFLASHER_REPO_SHIP" ] || BEAMOS_SHIELDFLASHER_REPO_SHIP=https://github.com/mrbeam/shield_flasher.git

[ -n "$BEAMOS_INCLUDE_RPI_WS281X" ] || BEAMOS_INCLUDE_RPI_WS281X=yes
[ -n "$BEAMOS_RPI_WS281X_ARCHIVE" ] || BEAMOS_RPI_WS281X_ARCHIVE=https://github.com/mrbeam/rpi_ws281x/archive/$BEAMOS_RPI_WS281X_REPO_BRANCH.zip
[ -n "$BEAMOS_RPI_WS281X_REPO_BUILD" ] || BEAMOS_RPI_WS281X_REPO_BUILD=https://github.com/mrbeam/rpi_ws281x.git
[ -n "$BEAMOS_RPI_WS281X_REPO_SHIP" ] || BEAMOS_RPI_WS281X_REPO_SHIP=https://github.com/mrbeam/rpi_ws281x.git

[ -n "$BEAMOS_INCLUDE_MOUNTMANAGER" ] || BEAMOS_INCLUDE_MOUNTMANAGER=yes
[ -n "$BEAMOS_MOUNTMANAGER_ARCHIVE" ] || BEAMOS_MOUNTMANAGER_ARCHIVE=https://github.com/mrbeam/usb_mount_manager/archive/$BEAMOS_MOUNTMANAGER_REPO_BRANCH.zip
[ -n "$BEAMOS_MOUNTMANAGER_REPO_BUILD" ] || BEAMOS_MOUNTMANAGER_REPO_BUILD=git+ssh://git@bitbucket.org/mrbeam/usb_mount_manager.git
[ -n "$BEAMOS_MOUNTMANAGER_REPO_SHIP" ] || BEAMOS_MOUNTMANAGER_REPO_SHIP=git+ssh://git@bitbucket.org/mrbeam/usb_mount_manager.git

[ -n "$BEAMOS_I2C_BAUDRATE" ] || BEAMOS_I2C_BAUDRATE=64000

# [ -n "$BEAMOS_INCLUDE_MRBEAMPLUGIN" ] || export BEAMOS_INCLUDE_MRBEAMPLUGIN=yes
# if [ ! -n "$BEAMOS_INCLUDE_MRBEAMPLUGIN" ]; then
#   [ -d "$MRBPLUGIN_PATH" ] || git clone git clone git@bitbucket.org:mrbeam/usb_mount_manager.git "$MRBPLUGIN_PATH"
#   pushd $MRBPLUGIN_PATH
#     # Checkout latest release in the case of the beta program
#     [ "$BEAMOS_BRANCH" == "stable" ]  && branch="mrbeam2-stable"
#     [ "$BEAMOS_BRANCH" == "beta" ]    && branch="$(wget -q -O - https://api.github.com/repos/mrbeam/MrBeamPlugin/releases/latest | grep 'tag_name' | cut -d : -f 2,3 | tr -d \" | tr -d ,)"
#     [ "$BEAMOS_BRANCH" == "develop" ] && branch="develop"
#     sudo -u $TRUE_USER git checkout $branch
#     sudo -u $TRUE_USER git pull || echo "Could not pull the remote repository, ignoring..."
#   popd
# fi
# BEAMOS_MRBEAMPLUGIN_ARCHIVE="${PIP_CHROOT_LOCAL_DEST}/MrBeamPlugin"

# # IoBeam
# [ -n "$BEAMOS_INCLUDE_IOBEAM" ] || export BEAMOS_INCLUDE_IOBEAM=yes
# if [ ! -n "$BEAMOS_INCLUDE_IOBEAM" ]; then
#   [ -d "$IOBEAM_PATH" ] || git clone git clone git@bitbucket.org:mrbeam/usb_mount_manager.git "$IOBEAM_PATH"
#   pushd $IOBEAM_PATH
#     [ "$BEAMOS_BRANCH" == "stable" ]  && branch="mrbeam2-stable"
#     [ "$BEAMOS_BRANCH" == "beta" ]    && branch="mrbeam2-beta"
#     [ "$BEAMOS_BRANCH" == "develop" ] && branch="develop"
#     sudo -u $TRUE_USER git checkout $branch
#     sudo -u $TRUE_USER git pull || echo "Could not pull the remote repository, ignoring..."
#   popd
# fi
# BEAMOS_IOBEAM_ARCHIVE="${PIP_CHROOT_LOCAL_DEST}/iobeam"

# # OpenCV
# [ -n "$BEAMOS_OPTIMISED_OPENCV" ] || BEAMOS_OPTIMISED_OPENCV=yes

# # USB Mount Manager
# [ -n "$BEAMOS_INCLUDE_MOUNTMANAGER" ] || BEAMOS_INCLUDE_MOUNTMANAGER=yes
# if [ ! -n "$BEAMOS_INCLUDE_MOUNTMANAGER" ]; then
#   [ -d "$MOUNTMANAGER_PATH" ] \
#     || git clone git clone git@bitbucket.org:mrbeam/usb_mount_manager.git "$MOUNTMANAGER_PATH" \
#     || (echo "ERROR - local repo not found and could not clone remote location" && exit 1)
#   pushd $MOUNTMANAGER_PATH
#     sudo -u $TRUE_USER git pull || echo "Could not pull the remote repository, ignoring..."
#   popd
# fi

# # Netconnectd
# [ -n "$BEAMOS_INCLUDE_NETCONNECTD" ] ||  BEAMOS_INCLUDE_NETCONNECTD=yes

# # Save the commit version of BEAMOS
# [ -n "$BEAMOS_COMMIT" ] || BEAMOS_COMMIT=`pushd "${DIST_PATH}" > /dev/null ; git rev-parse HEAD ; popd > /dev/null`

# # Set default parameters if DEV version
# if [ "$BEAMOS_DEV" == "yes" ]; then
#   BEAMOS_INCLUDE_SSH=yes
#   echo "TODO"
# fi
