#!/bin/sh

#################################################################
# Choose what to install here

TRUE_USER=pi

# Branches
[ -n "$BEAMOS_MRBEAMPLUGIN_REPO_BRANCH" ] || BEAMOS_MRBEAMPLUGIN_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_MRBEAMIOBEAM_REPO_BRANCH" ] || BEAMOS_IOBEAM_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_MRBEAMLED_REPO_BRANCH" ] || BEAMOS_MRBEAMLED_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_USBMOUNTMANAGER_REPO_BRANCH" ] || BEAMOS_MOUNTMANAGER_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_FINDMYMRBEAM_PLUGIN_REPO_BRANCH" ] || BEAMOS_FINDMYMRBEAM_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_NETCONNECTD_REPO_BRANCH" ] || BEAMOS_NETCONNECTD_REPO_BRANCH=master
[ -n "$BEAMOS_NETCONNECTD_PLUGIN_REPO_BRANCH" ] || BEAMOS_NETCONNECTD_PLUGIN_REPO_BRANCH=mrbeam2-stable-buster
[ -n "$BEAMOS_SHIELDFLASHER_REPO_BRANCH" ] || BEAMOS_SHIELDFLASHER_REPO_BRANCH=master
[ -n "$BEAMOS_RPI_WS281X_REPO_BRANCH" ] || BEAMOS_RPI_WS281X_REPO_BRANCH=master
[ -n "$BEAMOS_MRBEAMPLUGIN_DOCS_REPO_BRANCH" ] || BEAMOS_MRBEAMPLUGIN_DOCS_REPO_BRANCH=mrbeam2-stable
[ -n "$BEAMOS_CHECK_REPO_BRANCH" ] || BEAMOS_CHECK_REPO_BRANCH=master
[ -n "$BEAMOS_NETCONNECTD_WIFI_REPO_BRANCH" ] || BEAMOS_NETCONNECTD_WIFI_REPO_BRANCH=master

# # MrBeamPlugin
[ -n "$BEAMOS_INCLUDE_MRBEAMPLUGIN" ] || BEAMOS_INCLUDE_MRBEAMPLUGIN=yes
# This uses the latest release as an archive
# [ -n "$BEAMOS_MRBEAMPLUGIN_ARCHIVE" ] || export BEAMOS_MRBEAMPLUGIN_ARCHIVE=$(wget -q -O - https://api.github.com/repos/mrbeam/MrBeamPlugin/releases/latest | grep "zipball_url" | cut -d : -f 2,3 | tr -d \" | tr -d ,)
[ -n "$BEAMOS_MRBEAMPLUGIN_ARCHIVE" ] || BEAMOS_MRBEAMPLUGIN_ARCHIVE=https://github.com/mrbeam/MrBeamPlugin/archive/$BEAMOS_MRBEAMPLUGIN_REPO_BRANCH.zip
[ -n "$BEAMOS_MRBEAMPLUGIN_REPO_SHIP" ] || BEAMOS_MRBEAMPLUGIN_REPO_SHIP=https://github.com/mrbeam/MrBeamPlugin.git
[ -n "$BEAMOS_MRBEAMPLUGIN_REPO_BUILD" ] || BEAMOS_MRBEAMPLUGIN_REPO_BUILD=https://github.com/mrbeam/MrBeamPlugin.git
# Mr Beam Docs
[ -n "$BEAMOS_MRBEAMPLUGIN_DOCS_ARCHIVE" ] || BEAMOS_MRBEAMPLUGIN_DOCS_ARCHIVE=https://github.com/mrbeam/MrBeamDoc/archive/$BEAMOS_MRBEAMPLUGIN_DOCS_REPO_BRANCH.zip
[ -n "$BEAMOS_MRBEAMPLUGIN_DOCS_REPO_SHIP" ] || BEAMOS_MRBEAMPLUGIN_DOCS_REPO_SHIP=https://github.com/mrbeam/MrBeamDoc.git
[ -n "$BEAMOS_MRBEAMPLUGIN_DOCS_REPO_BUILD" ] || BEAMOS_MRBEAMPLUGIN_DOCS_REPO_BUILD=https://github.com/mrbeam/MrBeamDoc.git

# IOBeam
[ -n "$BEAMOS_INCLUDE_IOBEAM" ] || BEAMOS_INCLUDE_IOBEAM=yes
[ -n "$BEAMOS_IOBEAM_ARCHIVE" ] || BEAMOS_IOBEAM_ARCHIVE=https://github.com/mrbeam/iobeam/archive/$BEAMOS_IOBEAM_REPO_BRANCH.zip
[ -n "$BEAMOS_IOBEAM_REPO_BUILD" ] || BEAMOS_IOBEAM_REPO_BUILD=git+ssh://git@bitbucket.org/mrbeam/iobeam.git
[ -n "$BEAMOS_IOBEAM_REPO_SHIP" ] || BEAMOS_IOBEAM_REPO_SHIP=git+ssh://git@bitbucket.org/mrbeam/iobeam.git

[ -n "$BEAMOS_INCLUDE_MRBEAMLED" ] || BEAMOS_INCLUDE_MRBEAMLED=yes
[ -n "$BEAMOS_MRBEAMLED_ARCHIVE" ] || BEAMOS_MRBEAMLED_ARCHIVE=https://github.com/mrbeam/MrBeamLedStrips/archive/$BEAMOS_MRBEAMLED_REPO_BRANCH.zip
[ -n "$BEAMOS_MRBEAMLED_REPO_BUILD" ] || BEAMOS_MRBEAMLED_REPO_BUILD=https://github.com/mrbeam/MrBeamLedStrips.git
[ -n "$BEAMOS_MRBEAMLED_REPO_SHIP" ] || BEAMOS_MRBEAMLED_REPO_SHIP=https://github.com/mrbeam/MrBeamLedStrips.git

# Netconnectd and Netconnectd plugin
[ -n "$BEAMOS_INCLUDE_NETCONNECTD" ] || BEAMOS_INCLUDE_NETCONNECTD=yes
#   Wifi package for netconnectd
[ -n "$BEAMOS_NETCONNECTD_WIFI_ARCHIVE" ] || BEAMOS_NETCONNECTD_WIFI_ARCHIVE=https://github.com/mrbeam/wifi/archive/$BEAMOS_NETCONNECTD_WIFI_REPO_BRANCH.zip
[ -n "$BEAMOS_NETCONNECTD_ARCHIVE" ] || BEAMOS_NETCONNECTD_ARCHIVE=https://github.com/mrbeam/netconnectd_mrbeam/archive/$BEAMOS_NETCONNECTD_REPO_BRANCH.zip
[ -n "$BEAMOS_NETCONNECTD_REPO_BUILD" ] || BEAMOS_NETCONNECTD_REPO_BUILD=https://github.com/mrbeam/netconnectd_mrbeam.git
[ -n "$BEAMOS_NETCONNECTD_REPO_SHIP" ] || BEAMOS_NETCONNECTD_REPO_SHIP=https://github.com/mrbeam/netconnectd_mrbeam.git
[ -n "$BEAMOS_NETCONNECTD_VENV" ] || BEAMOS_NETCONNECTD_VENV=/usr/local/netconnectd/venv

[ -n "$BEAMOS_NETCONNECTD_PLUGIN_ARCHIVE" ] || BEAMOS_NETCONNECTD_PLUGIN_ARCHIVE=https://github.com/mrbeam/OctoPrint-Netconnectd/archive/$BEAMOS_NETCONNECTD_PLUGIN_REPO_BRANCH.zip
[ -n "$BEAMOS_NETCONNECTD_PLUGIN_REPO_BUILD" ] || BEAMOS_NETCONNECTD_PLUGIN_REPO_BUILD=https://github.com/mrbeam/OctoPrint-Netconnectd.git
[ -n "$BEAMOS_NETCONNECTD_PLUGIN_REPO_SHIP" ] || BEAMOS_NETCONNECTD_PLUGIN_REPO_SHIP=https://github.com/mrbeam/OctoPrint-Netconnectd.git

[ -n "$BEAMOS_INCLUDE_FINDMYMRBEAM" ] || BEAMOS_INCLUDE_FINDMYMRBEAM=yes
[ -n "$BEAMOS_FINDMYMRBEAM_ARCHIVE" ] || BEAMOS_FINDMYMRBEAM_ARCHIVE=https://github.com/mrbeam/OctoPrint-FindMyMrBeam/archive/$BEAMOS_FINDMYMRBEAM_REPO_BRANCH.zip
[ -n "$BEAMOS_FINDMYMRBEAM_REPO_BUILD" ] || BEAMOS_FINDMYMRBEAM_REPO_BUILD=https://github.com/mrbeam/OctoPrint-FindMyMrBeam.git
[ -n "$BEAMOS_FINDMYMRBEAM_REPO_SHIP" ] || BEAMOS_FINDMYMRBEAM_REPO_SHIP=https://github.com/mrbeam/OctoPrint-FindMyMrBeam.git

[ -n "$BEAMOS_INCLUDE_SHIELDFLASHER" ] || BEAMOS_INCLUDE_SHIELDFLASHER=yes
[ -n "$BEAMOS_SHIELDFLASHER_ARCHIVE" ] || BEAMOS_SHIELDFLASHER_ARCHIVE=https://github.com/mrbeam/shield_flasher/archive/$BEAMOS_SHIELDFLASHER_REPO_BRANCH.zip
[ -n "$BEAMOS_SHIELDFLASHER_REPO_BUILD" ] || BEAMOS_SHIELDFLASHER_REPO_BUILD=https://github.com/mrbeam/shield_flasher.git
[ -n "$BEAMOS_SHIELDFLASHER_REPO_SHIP" ] || BEAMOS_SHIELDFLASHER_REPO_SHIP=https://github.com/mrbeam/shield_flasher.git

[ -n "$BEAMOS_INCLUDE_RPI_WS281X" ] || BEAMOS_INCLUDE_RPI_WS281X=yes
[ -n "$BEAMOS_RPI_WS281X_ARCHIVE" ] || BEAMOS_RPI_WS281X_ARCHIVE=https://github.com/mrbeam/rpi_ws281x/archive/$BEAMOS_RPI_WS281X_REPO_BRANCH.zip
[ -n "$BEAMOS_RPI_WS281X_REPO_BUILD" ] || BEAMOS_RPI_WS281X_REPO_BUILD=https://github.com/mrbeam/rpi_ws281x.git
[ -n "$BEAMOS_RPI_WS281X_REPO_SHIP" ] || BEAMOS_RPI_WS281X_REPO_SHIP=https://github.com/mrbeam/rpi_ws281x.git

[ -n "$BEAMOS_INCLUDE_MOUNTMANAGER" ] || BEAMOS_INCLUDE_MOUNTMANAGER=yes
[ -n "$BEAMOS_MOUNTMANAGER_ARCHIVE" ] || BEAMOS_MOUNTMANAGER_ARCHIVE=https://github.com/mrbeam/usb_mount_manager/archive/$BEAMOS_MOUNTMANAGER_REPO_BRANCH.zip
[ -n "$BEAMOS_MOUNTMANAGER_REPO_BUILD" ] || BEAMOS_MOUNTMANAGER_REPO_BUILD=git+ssh://git@bitbucket.org/mrbeam/usb_mount_manager.git
[ -n "$BEAMOS_MOUNTMANAGER_REPO_SHIP" ] || BEAMOS_MOUNTMANAGER_REPO_SHIP=git+ssh://git@bitbucket.org/mrbeam/usb_mount_manager.git

[ -n "$BEAMOS_INCLUDE_CHECK" ] || BEAMOS_INCLUDE_CHECK=yes
[ -n "$BEAMOS_CHECK_ARCHIVE" ] || BEAMOS_CHECK_ARCHIVE=https://github.com/mrbeam/mrb_check/archive/$BEAMOS_CHECK_REPO_BRANCH.zip
[ -n "$BEAMOS_CHECK_REPO_BUILD" ] || BEAMOS_CHECK_REPO_BUILD=git+ssh://git@github.com:mrbeam/mrb_check.git
[ -n "$BEAMOS_CHECK_REPO_SHIP" ] || BEAMOS_CHECK_REPO_SHIP=git+ssh://git@github.com:mrbeam/mrb_check.git
### Misc

[ -n "$BEAMOS_DEV" ] || BEAMOS_DEV=yes
[ -n "$BEAMOS_I2C_BAUDRATE" ] || BEAMOS_I2C_BAUDRATE=64000
