name: Build Image

on: 
  push:
    branches:
      - mrbeam
    paths-ignore:
      - '*.rst'
      - '*.md'
  schedule:
    - cron: '0 0 * * *'
env:
  VARIANT: beamos


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavors: ["2S", "develop 2S"]
        # flavors: ["develop 2S"]
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'mrbeam/CustomPiOS'
        path: CustomPiOS
        ref: 'mrbeam'

    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_MRB }}
        submodules: recursive
        path: repository

    - name: Write submodule info to separate files outside chroot
      run: |
        cd repository
        git --no-pager submodule foreach 'git branch | tail -n 1 | tee current_branch'
        git --no-pager submodule foreach 'git  rev-parse HEAD | tee current_commit_hash'

    - name: Download Raspbian Image
      run: |
        cd repository/src/image
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths

    - name: Force apt mirror to work around intermittent mirror hiccups
      run: |
        echo "OCTOPI_APTMIRROR=http://mirror.us.leaseweb.net/raspbian/raspbian" > repository/src/config.local

    - name: Build Image (MrBeam Variant)
      run: |
        sudo modprobe loop
        cd repository/src
        sudo bash -x EXTRA_SSH_KEY="${{ secrets.SSH_BEAMOS01_RSA }}" ./build_dist $VARIANT ${{ matrix.flavors }}

    - name: Copy output
      id: copy
      run: |
        source repository/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        # When building a variant, it is built in workspace-$VARIANT
        if [ -n $VARIANT ]; then
          [ -n "${{ matrix.flavors }}" ] && FL="$(echo ${{ matrix.flavors }} | sed 's/ /-/g')-"
          IMAGE=$NOW-$VARIANT-$FL$DIST_VERSION
          cp repository/src/workspace-$VARIANT/*.img $IMAGE.img
        else
          IMAGE=$NOW-octopi-$DIST_VERSION
          cp repository/src/workspace/*.img $IMAGE.img
        fi

        echo "::set-output name=image::$IMAGE"

    # artifact upload will take care of zipping for us
    - uses: actions/upload-artifact@v1
      # if: github.event_name == 'schedule'
      with:
        name: ${{ steps.copy.outputs.image }}
        path: ${{ steps.copy.outputs.image }}.img
